---
version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    #network_mode: host
    ports:
      - 32410:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - ./plexconfig:/config
      - ../downloads/seriados:/tv
      - ../downloads/filmes:/movies
    restart: unless-stopped