apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  labels:
    app: plex
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  labels:
    app: plex
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv
  labels:
    app: plex
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi