---
version: "2.1"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo 
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=duran #optional
      - PASS=skazi12 #optional
    volumes:
      - ./config:/config
      - ../downloads:/downloads
      - ../downloads:/watch
      - ../downloads/filmes:/filmes
      - ../downloads/seriados:/seriados
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped